[package]
name = "thurin_helper"
type = "bin"
authors = ["Thurin Contributors"]
compiler_version = ">=0.36.0"

[dependencies]
poseidon = { tag = "v0.2.0", git = "https://github.com/noir-lang/poseidon" }
