[package]
name = "thurin"
type = "bin"
authors = ["Thurin Contributors"]
compiler_version = ">=0.36.0"

[dependencies]
sha256 = { tag = "v0.3.0", git = "https://github.com/noir-lang/sha256" }
poseidon = { tag = "v0.2.0", git = "https://github.com/noir-lang/poseidon" }
